variables:
  FW_VERSION_PS: '.scripts\fw-version.ps1'
  CORE_VERSION_PS: '.scripts\core-version.ps1'
  PACKAGE_PS: '.scripts\package.ps1'
  DEFAULT_SLN: 'GoC.WebTemplate.sln'
  xUNIT_PATH: 'packages\xunit.runner.console.2.4.1\tools\net461'
  TEST_FRAME_PATH: 'Components.Framework.Tests\bin\Release'
  ARTIFACTORY_DEPLOY: 'https://jade-repos.intra.dev/artifactory/ca-gc-sds-libs-nuget-local/'
  
stages:
  - Prepare
  - Build
  - Test
  - Package
  - Deploy

include:
  - local: '/.gitlab/ci/prepare.gitlab-ci.yml'
  - local: '/.gitlab/ci/build.gitlab-ci.yml'
  - local: '/.gitlab/ci/test.gitlab-ci.yml'
  - local: '/.gitlab/ci/package.gitlab-ci.yml'
  - local: '/.gitlab/ci/deploy.gitlab-ci.yml'

.secrets:
  before_script:
    - 'copy %SECRETS_PATH%\\GoC.WebTemplate.snk .'
  after_script:
    - 'del GoC.WebTemplate.snk'