variables:
  VERSION_PS1: 'Builds\\version.ps1'
  PACKAGE_PS1: 'Builds\\package.ps1'
  DEFAULT_SLN: 'GoC.WebTemplate.sln'
  SAMPLES_SLN: 'GoC.WebTemplate.Samples.sln'
  ARTIFACTORY_DEPLOY: 'https://jade-repos.intra.dev/artifactory/ca-gc-sds-libs-nuget-local/'
  # variables from runner
  # - NUGET_PATH
  # - MSBUILD_PATH
  # - CURL_PATH
  # - ARTIFACTORY_CRED
  
stages:
  - prepare
  - build
  - test
  - package
  - deploy

include:
  - local: '/Builds/prepare.gitlab-ci.yml'
  - local: '/Builds/build.gitlab-ci.yml'
  - local: '/Builds/test.gitlab-ci.yml'
  # - local: '/Builds/package.gitlab-ci.yml'

# deploy:
#   stage: deploy
#   dependencies: 
#     - package_components
#     - package_mvc
#     - package_forms
#     - package_mvc_sample
#     - package_forms_sample
#   tags:
#     - artifactory
#     - curl
#   environment:
#     name: Artifactory
#     url: '%ARTIFACTORY_DEPLOY%'
#   only:
#     - tags
#   script:
#     - '"%CURL_PATH%" -u %RUNNER_USER_CRED% -X PUT %ARTIFACTORY_DEPLOY% -T GoC.WebTemplate-Components.%CI_COMMIT_REF_NAME%.nupkg -k'
#     - '"%CURL_PATH%" -u %RUNNER_USER_CRED% -X PUT %ARTIFACTORY_DEPLOY% -T GoC.WebTemplate-WebForms.%CI_COMMIT_REF_NAME%.nupkg -k'
#     - '"%CURL_PATH%" -u %RUNNER_USER_CRED% -X PUT %ARTIFACTORY_DEPLOY% -T GoC.WebTemplate-MVC.%CI_COMMIT_REF_NAME%.nupkg -k'
#     - '"%CURL_PATH%" -u %RUNNER_USER_CRED% -X PUT %ARTIFACTORY_DEPLOY% -T GoC.WebTemplate-WebForms.Sample.%CI_COMMIT_REF_NAME%.nupkg -k'
#     - '"%CURL_PATH%" -u %RUNNER_USER_CRED% -X PUT %ARTIFACTORY_DEPLOY% -T GoC.WebTemplate-MVC.Sample.%CI_COMMIT_REF_NAME%.nupkg  -k'
