.unit_test:
  stage: Test
  extends: .secrets
  tags:
    - secrets
    - dotnet
    - ps
  script:
    - dotnet test $env:PROJECT --logger "junit;LogFilePath=UnitTestResults.xml"
  artifacts:
    reports:
      junit: $env:PROJECT\UnitTestResults.xml

Unit_Test:Components:
  extends: .unit_test
  variables:
    PROJECT: Components.Tests

Unit_Test:Components.Core:
  extends: .unit_test
  variables:
    PROJECT: Components.Core.Tests

Unit_Test:Components.Framework:
  stage: Test
  tags:
    - ps
  dependencies:
    - Compile:Default_SLN
  script:
    - '"$env:xUNIT_PATH\xunit.console.exe" "$env:TEST_FRAME_PATH\GoC.WebTemplate.Components.Framework.Tests.dll" -junit ComponentsFrameworkTestResults.xml'
  artifacts:
    reports:
      junit: ComponentsFrameworkTestResults.xml
